service: serverless-project
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  environment:
    TABLE_NAME: 'AuctionTable-dev'
    BUCKET_NAME: 'sls-project-gokul'

plugins:
  - serverless-offline

functions:
  QueryItem:
    handler: src/Posts/queryItem.handler
    events:
      - http:
          path: /queryItem
          method: GET

  GetItem:
    handler: src/Posts/getItem.handler
    events:
      - http:
          path: /getItem
          method: GET
      - http:
          path: /getItem
          method: POST

  PutItem:
    handler: src/Posts/putItem.handler
    events:
      - http:
          path: /putItem
          method: POST
      - http:
          path: /putItem
          method: PUT

  deleteItem:
    handler: src/Posts/deleteItem.handler
    events:
      - http:
          path: /deleteItem
          method: DELETE
  uploadFile:
    handler: src/Posts/bucketHandler.uploadFile
    events:
      - http:
          path: /upload
          method: POST
  removeFile:
    handler: src/Posts/bucketHandler.removeFile
    events: 
      - http:
          path: /remove
          method: DELETE
  getFileContent:
    handler: src/Posts/bucketHandler.displayContent
    events:
      - http:
          path: /getcontent
          method: POST
        